version: 0.2

env:
    variables:
        BUILD_FOLDER: "personal-website/dist"
phases:
    install:
        on-failure: ABORT
        runtime-versions:
            nodejs: 12
        commands:
            - cd personal-website
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        on-failure: ABORT
        commands:
            - echo Build started on `date`
            - ng build --prod=true
    post_build:
        commands:
            - aws s3 rm s3://luispetitjean.com --recursive
artifacts:
    files:
        - '**/*'
    base-directory: ${BUILD_FOLDER}