version: 0.2

env:
    variables:
        BUILD_FOLDER: "personal-website/dist"
phases:
    install:
        on-failure: ABORT
        runtime-versions:
            nodejs: 16
        commands:
            - cd personal-website
            - echo Installing source NPM dependencies...
            - npm install
    build:
        on-failure: ABORT
        commands:
            - echo Build started on `date`
            - npx ng build --configuration production
artifacts:
    files:
        - '**/*'
    base-directory: ${BUILD_FOLDER}