version: 0.2

env:
    variables:
        BUILD_FOLDER: "dist/personal-website"
phases:
    install:
        runtime-versions:
            nodejs:10
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build
artifacts:
    files:
        - '**/*'
    base-directory: ${BUILD_FOLDER}
    discard-paths: yes