version: 0.2

env:
    variables:
        BUILD_FOLDER: "personal-website/dist"
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - cd personal-website
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --prod=true
    post_build:
        commands:
            - aws s3 rm --recursive "s3://luispetitjean.com" 
artifacts:
    files:
        - '**/*'
    base-directory: ${BUILD_FOLDER}